### ISSUE TITLE
Pacemaker-1.0.10  has pacemaker 1.0.9

### ISSUE THREAD

**Issue by ghost** [ClusterLabs/pacemaker-1.0#19]
Hi, 

The Pacemaker-1.0.10  file from releases compiles pacemaker version 1.0.9, is there any way to get 1.0.10 ?

**Comment by kgaillot** [comment]
That code base is long dead and unsupported. It's best avoided in favor of the ClusterLabs/pacemaker repository.

I'm guessing you mean that if you checkout the Pacemaker-1.0.10 tag and compile, pacemaker reports its version as 1.0.9. There was an oversight in 1.0.10 where the version number wasn't updated in configure.ac. It reports 1.0.9, but it is different. If you really want to compile a version that reports 1.0.10, just update configure.ac before building.
